image:
  repository: me-central2-docker.pkg.dev/rahafawadallah-jy0lla/demo-app/app
  tag: "85fb5d6"
  pullPolicy: IfNotPresent
replicaCount: 1
service:
  type: ClusterIP
  port: 80
containerPort: 8080
resources: {}
