image:
  repository: me-central2-docker.pkg.dev/YOUR-PROJECT/demo-app/app
  tag: "dev"
  pullPolicy: IfNotPresent

replicaCount: 1
service:
  type: ClusterIP
  port: 80
containerPort: 8080
resources: {}
